name: Metrics
on:

  schedule: [{cron: "0 0 * * *"}]
 
  workflow_dispatch:

  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-iso.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: UmutcanElci
          
    
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      
      - name: Languages Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: UmutcanElci
          
         
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
